name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install other prereqs
        run: |
          echo "$RUNNER_OS";
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install cairo
            brew install pango
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo snap install snapcraft --classic
          fi
        shell: bash 

      - name: Install dependencies
        run: npm install && npm run install

      - name: Release Electron app
        run: npm run package
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
