name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Build game library
        working-directory: ./game/
        run: npm install && npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Build/release Electron app
        working-directory: ./editor/
        run: npm install && npm run build && npx electron-builder
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
