name: Build/test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # windows fails due to jest configuration?
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install other prereqs
        run: |
          echo "$RUNNER_OS";
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install cairo
            brew install pango
          fi
        shell: bash 

      - name: Install dependencies
        run: npm install && npm run install

      - name: Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm test

